# Generated by Django 4.2.2 on 2023-06-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
    ]
